# Assignment 4

Ques 1)Write a program to create a NumPy 1D-array with 5 elements and perform basic
operations like:
1. Addition of 2 in all the element
2. Multiply 3 with all the elements
3. Divide every element by 2

In [1]:
import numpy as np

a = [1,2,3,4,5]
arr = np.array(a)

print(f"1. {arr[1] + arr[2]}")
print(f"2. {arr * 3}")
print(f"3. {arr / 2}")


1. 5
2. [ 3  6  9 12 15]
3. [0.5 1.  1.5 2.  2.5]


Ques 2)Questions on Basic NumPy Array: <br>
a. Reverse the NumPy array: arr = np.array([1, 2, 3, 6, 4, 5]) <br>
b. Find the most frequent value and their indice(s) in the following arrays: <br>
    i. x = np.array([1,2,3,4,5,1,2,1,1,1])  <br>
    ii. y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ])

In [2]:
arr = np.array([1,2,3,4,5])
print(f"Reversed array: {np.flip(arr)}")

x = np.array([1,2,3,4,5,1,2,1,1,1])
unq_x, counts_x = np.unique(x, return_counts=True)
max_counts_x = np.argmax(counts_x)
max_element_x = unq_x[max_counts_x]
print(f"Most frequent element in x: {max_element_x}, with a frequency of: {counts_x[max_counts_x]}")

y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ])
unq_y, counts_y = np.unique(y, return_counts=True)
max_counts_y = np.argmax(counts_y)
max_element_y = unq_y[max_counts_y]
print(f"Most frequent element in x: {max_element_y}, with a frequency of: {counts_y[max_counts_y]}")

Reversed array: [5 4 3 2 1]
Most frequent element in x: 1, with a frequency of: 5
Most frequent element in x: 1, with a frequency of: 3


Ques 3) For the given 2-D array arr=np.array([10, 20, 30], [40, 50, 60], [70, 80, 90]), access
elements using row and column indices as follows:
1. Access 1st row, 2nd column
2. Access 3rd row, 1st column

In [3]:
arr2d = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])

print(f"1. {arr2d[0][1]}")
print(f"2. {arr2d[2][0]}")


1. 20
2. 70


Ques 4) Write program to create an 1-D NumPy array named _Your Name_ with evenly
spaced 25 numbers from 10 to 100 using linspace(). 
- Print the dimensions of the array, shape, total elements, the data type of each element and total number of bytes consumed
by the array. 
- Find the transpose of this array using reshape() attribute. Can we do the same
with T attribute?

In [2]:
import numpy as np

Shrey = np.array(np.linspace(10, 100, 25), dtype=np.float64)  # Explicit dtype

print(f"i.\nDimensions: {Shrey.ndim}")
print(f"Shape: {Shrey.shape}")
print(f"Number of elements: {Shrey.size}")
print(f"Datatype: {Shrey.dtype}")
print(f"Number of Bytes occupied: {Shrey.nbytes}")

Shrey_reshaped = Shrey.reshape(5, 5)
print(f"ii. Transpose using reshape:\n{Shrey_reshaped}")

Shrey_T = Shrey_reshaped.T
print(f"Transpose using T attribute:\n{Shrey_T}")


i.
Dimensions: 1
Shape: (25,)
Number of elements: 25
Datatype: float64
Number of Bytes occupied: 200
ii. Transpose using reshape:
[[ 10.    13.75  17.5   21.25  25.  ]
 [ 28.75  32.5   36.25  40.    43.75]
 [ 47.5   51.25  55.    58.75  62.5 ]
 [ 66.25  70.    73.75  77.5   81.25]
 [ 85.    88.75  92.5   96.25 100.  ]]
Transpose using T attribute:
[[ 10.    28.75  47.5   66.25  85.  ]
 [ 13.75  32.5   51.25  70.    88.75]
 [ 17.5   36.25  55.    73.75  92.5 ]
 [ 21.25  40.    58.75  77.5   96.25]
 [ 25.    43.75  62.5   81.25 100.  ]]


Ques 5) Create a 2-D Array of three rows and four columns, named _ucs420<< yourname >>_ with following values – 10, 20, 30, 40, 50, 60, 70, 80, 90, 15, 20, 35. <br>Compute the mean,
median, max, min, unique elements. Reshape the array to four rows and three columns and
name it as reshaped _ucs420<< your_name >>_. Resize the array to two rows and three
columns and name it as resized _ucs420<< your_name >>_.

In [ ]:
import numpy as np

ucs420_Shrey = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 15, 20, 35])

print(f"Mean: {ucs420_Shrey.mean():.3f}")
print(f"Median: {np.median(ucs420_Shrey)}")
print(f"Max: {ucs420_Shrey.max()}")
print(f"Min: {ucs420_Shrey.min()}")

print(f"Standard Deviation: {ucs420_Shrey.std():.3f}")
print(f"Variance: {ucs420_Shrey.var():.3f}")

unique_elements = np.unique(ucs420_Shrey)
print(f"Unique elements: {unique_elements}")

sorted_array = np.sort(ucs420_Shrey)
print(f"Sorted array: {sorted_array}")

if ucs420_Shrey.size == 4 * 3:
    reshaped_array = ucs420_Shrey.reshape(4, 3)
    print(f"Reshaped array (4x3):\n{reshaped_array}")
else:
    print("Reshape operation skipped: Invalid size.")

resized_array = np.resize(ucs420_Shrey, (2, 3))
print(f"Resized array (2x3):\n{resized_array}")


Mean: 43.333
Median: 37.5
Max: 90
Min: 10
Standard Deviation: 25.522
Variance: 651.389
Unique elements: [10 15 20 30 35 40 50 60 70 80 90]
Sorted array: [10 15 20 20 30 35 40 50 60 70 80 90]
Reshaped array (4x3):
[[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]
Resized array (2x3):
[[10 20 30]
 [40 50 60]]
