# Assignment 4


create and identity matrix 


In [8]:
import numpy as np

ones = np.ones(5, 5)
print("Ones array:")
print(ones)

zeros = np.zeros((5, 5))  
print("Zeros array:")
print(zeros)

Ones array:
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
Zeros array:
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
